name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'deploy') }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Set env
        run: |
          echo "slide=$(echo '${{ github.event.head_commit.message }}' | cut -d' ' -f 2)" >> $GITHUB_ENV

      - name: Install and Build 🔧
        run: |
          echo ${{ env.slide }}
          npm install
          npm run build -- ./slides/${{ env.slide }}.md --base /talks/${{ env.slide }}/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          target-folder: ${{ env.slide }}
          clean: false

      - name: Update README
        run: |
          echo "|${{ env.slide }}|-|-|[link](https://guisso.dev/talks/${{ env.slide }}/)|" >> README.md
      - name: Commit README changes
        use: stefanzweifel/git-auto-commit-action@v4
        commit_message: readme: add ${{ env.slide }} link
        file_pattern: README.md
